In [1]:
import numpy as np
data = [[1,2], [3,4], [5,6]]
data = np.array(data)
data[:,1]

array([2, 4, 6])

In [3]:
data = [[1,2], [3,4], [5,6]]
data = np.array(data)


In [5]:

[data[0][1], data[1][1], data[2][1]]

[2, 4, 6]

In [7]:

[data[0][1], data[1][1], data[2][1]]

[2, 4, 6]

In [11]:

data[:,1]

array([2, 4, 6])

In [13]:
data = [[1,2], [3,4], [5,6]]
data = np.array(data)

In [23]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
data.mean()

3.5

In [19]:
np.mean(data,1)

array([1.5, 3.5, 5.5])

In [21]:
data.mean(0)

array([3., 4.])